// This file was auto-generated by ML.NET Model Builder. 

using System;
using CryptoCoinPredictionML.Model;

namespace CryptoCoinPredictionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Open = 13761.5F,
                High = 13830F,
                Low = 13195.05F,
                Close = 13549.37F,
                VolumeBTC = 64566.42F,
                VolumeUSDT = 8.7363E+08F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual NextDayClose with predicted NextDayClose from sample data...\n\n");
            Console.WriteLine($"Open: {sampleData.Open}");
            Console.WriteLine($"High: {sampleData.High}");
            Console.WriteLine($"Low: {sampleData.Low}");
            Console.WriteLine($"Close: {sampleData.Close}");
            Console.WriteLine($"VolumeBTC: {sampleData.VolumeBTC}");
            Console.WriteLine($"VolumeUSDT: {sampleData.VolumeUSDT}");
            Console.WriteLine($"\n\nPredicted NextDayClose: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
